# Ruff configuration for MCP Server Blueprint
# https://docs.astral.sh/ruff/

line-length = 100
target-version = "py312"
src = ["src", "tests"]

[lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "UP",     # pyupgrade
    "ARG",    # flake8-unused-arguments
    "SIM",    # flake8-simplify
    "PTH",    # flake8-use-pathlib
    "PL",     # pylint
    "RUF",    # ruff-specific rules
]

ignore = [
    "E501",    # line too long (handled by formatter)
    "B008",    # do not perform function calls in argument defaults
    "PLR0913", # too many arguments to function call
    "PLR2004", # magic value used in comparison
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # unused imports in __init__.py are often intentional for re-exports
"tests/**/*.py" = [
    "ARG",     # unused arguments are common in test fixtures
    "PLR2004", # magic values are acceptable in tests
    "S101",    # use of assert is expected in tests
]

[lint.isort]
known-first-party = ["src"]
force-single-line = false
lines-after-imports = 2

[lint.pylint]
max-args = 8
max-branches = 15
max-returns = 8
max-statements = 60

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 80
